/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */
import { BhAccordionItem as BhAccordionItemElement, defineCustomElement as defineBhAccordionItem } from "@actabldesign/bellhop-core/components/bh-accordion-item.js";
import { BhAccordion as BhAccordionElement, defineCustomElement as defineBhAccordion } from "@actabldesign/bellhop-core/components/bh-accordion.js";
import { BhAppbar as BhAppbarElement, defineCustomElement as defineBhAppbar } from "@actabldesign/bellhop-core/components/bh-appbar.js";
import { BhAutocompleteMenu as BhAutocompleteMenuElement, defineCustomElement as defineBhAutocompleteMenu } from "@actabldesign/bellhop-core/components/bh-autocomplete-menu.js";
import { BhAvatarAdd as BhAvatarAddElement, defineCustomElement as defineBhAvatarAdd } from "@actabldesign/bellhop-core/components/bh-avatar-add.js";
import { BhAvatarStacked as BhAvatarStackedElement, defineCustomElement as defineBhAvatarStacked } from "@actabldesign/bellhop-core/components/bh-avatar-stacked.js";
import { BhAvatar as BhAvatarElement, defineCustomElement as defineBhAvatar } from "@actabldesign/bellhop-core/components/bh-avatar.js";
import { BhBadgeDot as BhBadgeDotElement, defineCustomElement as defineBhBadgeDot } from "@actabldesign/bellhop-core/components/bh-badge-dot.js";
import { BhBadge as BhBadgeElement, defineCustomElement as defineBhBadge } from "@actabldesign/bellhop-core/components/bh-badge.js";
import { BhBarChart as BhBarChartElement, defineCustomElement as defineBhBarChart } from "@actabldesign/bellhop-core/components/bh-bar-chart.js";
import { BhBreadcrumbs as BhBreadcrumbsElement, defineCustomElement as defineBhBreadcrumbs } from "@actabldesign/bellhop-core/components/bh-breadcrumbs.js";
import { BhButtonIcon as BhButtonIconElement, defineCustomElement as defineBhButtonIcon } from "@actabldesign/bellhop-core/components/bh-button-icon.js";
import { BhButton as BhButtonElement, defineCustomElement as defineBhButton } from "@actabldesign/bellhop-core/components/bh-button.js";
import { BhCardFooter as BhCardFooterElement, defineCustomElement as defineBhCardFooter } from "@actabldesign/bellhop-core/components/bh-card-footer.js";
import { BhCardHeader as BhCardHeaderElement, defineCustomElement as defineBhCardHeader } from "@actabldesign/bellhop-core/components/bh-card-header.js";
import { BhCard as BhCardElement, defineCustomElement as defineBhCard } from "@actabldesign/bellhop-core/components/bh-card.js";
import { BhChartTooltip as BhChartTooltipElement, defineCustomElement as defineBhChartTooltip } from "@actabldesign/bellhop-core/components/bh-chart-tooltip.js";
import { BhCheckboxGroupItem as BhCheckboxGroupItemElement, defineCustomElement as defineBhCheckboxGroupItem } from "@actabldesign/bellhop-core/components/bh-checkbox-group-item.js";
import { BhCheckboxGroup as BhCheckboxGroupElement, defineCustomElement as defineBhCheckboxGroup } from "@actabldesign/bellhop-core/components/bh-checkbox-group.js";
import { BhCheckbox as BhCheckboxElement, defineCustomElement as defineBhCheckbox } from "@actabldesign/bellhop-core/components/bh-checkbox.js";
import { BhContainerFooter as BhContainerFooterElement, defineCustomElement as defineBhContainerFooter } from "@actabldesign/bellhop-core/components/bh-container-footer.js";
import { BhContainer as BhContainerElement, defineCustomElement as defineBhContainer } from "@actabldesign/bellhop-core/components/bh-container.js";
import { BhDataGrid as BhDataGridElement, defineCustomElement as defineBhDataGrid } from "@actabldesign/bellhop-core/components/bh-data-grid.js";
import { BhDatePickerContent as BhDatePickerContentElement, defineCustomElement as defineBhDatePickerContent } from "@actabldesign/bellhop-core/components/bh-date-picker-content.js";
import { BhDatePicker as BhDatePickerElement, defineCustomElement as defineBhDatePicker } from "@actabldesign/bellhop-core/components/bh-date-picker.js";
import { BhDateRangePickerContent as BhDateRangePickerContentElement, defineCustomElement as defineBhDateRangePickerContent } from "@actabldesign/bellhop-core/components/bh-date-range-picker-content.js";
import { BhDateRangePicker as BhDateRangePickerElement, defineCustomElement as defineBhDateRangePicker } from "@actabldesign/bellhop-core/components/bh-date-range-picker.js";
import { BhDropdownMenu as BhDropdownMenuElement, defineCustomElement as defineBhDropdownMenu } from "@actabldesign/bellhop-core/components/bh-dropdown-menu.js";
import { BhDropdown as BhDropdownElement, defineCustomElement as defineBhDropdown } from "@actabldesign/bellhop-core/components/bh-dropdown.js";
import { BhEmptyState as BhEmptyStateElement, defineCustomElement as defineBhEmptyState } from "@actabldesign/bellhop-core/components/bh-empty-state.js";
import { BhFeaturedIcon as BhFeaturedIconElement, defineCustomElement as defineBhFeaturedIcon } from "@actabldesign/bellhop-core/components/bh-featured-icon.js";
import { BhIllustrations as BhIllustrationsElement, defineCustomElement as defineBhIllustrations } from "@actabldesign/bellhop-core/components/bh-illustrations.js";
import { BhInputAutocomplete as BhInputAutocompleteElement, defineCustomElement as defineBhInputAutocomplete } from "@actabldesign/bellhop-core/components/bh-input-autocomplete.js";
import { BhInputNumber as BhInputNumberElement, defineCustomElement as defineBhInputNumber } from "@actabldesign/bellhop-core/components/bh-input-number.js";
import { BhInputPassword as BhInputPasswordElement, defineCustomElement as defineBhInputPassword } from "@actabldesign/bellhop-core/components/bh-input-password.js";
import { BhInputText as BhInputTextElement, defineCustomElement as defineBhInputText } from "@actabldesign/bellhop-core/components/bh-input-text.js";
import { BhInputVerification as BhInputVerificationElement, defineCustomElement as defineBhInputVerification } from "@actabldesign/bellhop-core/components/bh-input-verification.js";
import { BhLabel as BhLabelElement, defineCustomElement as defineBhLabel } from "@actabldesign/bellhop-core/components/bh-label.js";
import { BhLoaderSpinner as BhLoaderSpinnerElement, defineCustomElement as defineBhLoaderSpinner } from "@actabldesign/bellhop-core/components/bh-loader-spinner.js";
import { BhLogoBox as BhLogoBoxElement, defineCustomElement as defineBhLogoBox } from "@actabldesign/bellhop-core/components/bh-logo-box.js";
import { BhModalActions as BhModalActionsElement, defineCustomElement as defineBhModalActions } from "@actabldesign/bellhop-core/components/bh-modal-actions.js";
import { BhModalHeader as BhModalHeaderElement, defineCustomElement as defineBhModalHeader } from "@actabldesign/bellhop-core/components/bh-modal-header.js";
import { BhModal as BhModalElement, defineCustomElement as defineBhModal } from "@actabldesign/bellhop-core/components/bh-modal.js";
import { BhMonthPickerContent as BhMonthPickerContentElement, defineCustomElement as defineBhMonthPickerContent } from "@actabldesign/bellhop-core/components/bh-month-picker-content.js";
import { BhMonthPicker as BhMonthPickerElement, defineCustomElement as defineBhMonthPicker } from "@actabldesign/bellhop-core/components/bh-month-picker.js";
import { BhNavItem as BhNavItemElement, defineCustomElement as defineBhNavItem } from "@actabldesign/bellhop-core/components/bh-nav-item.js";
import { BhNotification as BhNotificationElement, defineCustomElement as defineBhNotification } from "@actabldesign/bellhop-core/components/bh-notification.js";
import { BhPageNavigationChild as BhPageNavigationChildElement, defineCustomElement as defineBhPageNavigationChild } from "@actabldesign/bellhop-core/components/bh-page-navigation-child.js";
import { BhPageNavigationMultiLevel as BhPageNavigationMultiLevelElement, defineCustomElement as defineBhPageNavigationMultiLevel } from "@actabldesign/bellhop-core/components/bh-page-navigation-multi-level.js";
import { BhPageNavigationSingleLevel as BhPageNavigationSingleLevelElement, defineCustomElement as defineBhPageNavigationSingleLevel } from "@actabldesign/bellhop-core/components/bh-page-navigation-single-level.js";
import { BhPageNavigation as BhPageNavigationElement, defineCustomElement as defineBhPageNavigation } from "@actabldesign/bellhop-core/components/bh-page-navigation.js";
import { BhPagination as BhPaginationElement, defineCustomElement as defineBhPagination } from "@actabldesign/bellhop-core/components/bh-pagination.js";
import { BhPickerMenu as BhPickerMenuElement, defineCustomElement as defineBhPickerMenu } from "@actabldesign/bellhop-core/components/bh-picker-menu.js";
import { BhPieChart as BhPieChartElement, defineCustomElement as defineBhPieChart } from "@actabldesign/bellhop-core/components/bh-pie-chart.js";
import { BhPopover as BhPopoverElement, defineCustomElement as defineBhPopover } from "@actabldesign/bellhop-core/components/bh-popover.js";
import { BhProductSwitcher as BhProductSwitcherElement, defineCustomElement as defineBhProductSwitcher } from "@actabldesign/bellhop-core/components/bh-product-switcher.js";
import { BhPropertySwitcher as BhPropertySwitcherElement, defineCustomElement as defineBhPropertySwitcher } from "@actabldesign/bellhop-core/components/bh-property-switcher.js";
import { BhRadioButton as BhRadioButtonElement, defineCustomElement as defineBhRadioButton } from "@actabldesign/bellhop-core/components/bh-radio-button.js";
import { BhSidebar as BhSidebarElement, defineCustomElement as defineBhSidebar } from "@actabldesign/bellhop-core/components/bh-sidebar.js";
import { BhSkeletonLoader as BhSkeletonLoaderElement, defineCustomElement as defineBhSkeletonLoader } from "@actabldesign/bellhop-core/components/bh-skeleton-loader.js";
import { BhTabItem as BhTabItemElement, defineCustomElement as defineBhTabItem } from "@actabldesign/bellhop-core/components/bh-tab-item.js";
import { BhTabs as BhTabsElement, defineCustomElement as defineBhTabs } from "@actabldesign/bellhop-core/components/bh-tabs.js";
import { BhTag as BhTagElement, defineCustomElement as defineBhTag } from "@actabldesign/bellhop-core/components/bh-tag.js";
import { BhTextarea as BhTextareaElement, defineCustomElement as defineBhTextarea } from "@actabldesign/bellhop-core/components/bh-textarea.js";
import { BhToggle as BhToggleElement, defineCustomElement as defineBhToggle } from "@actabldesign/bellhop-core/components/bh-toggle.js";
import { BhTooltip as BhTooltipElement, defineCustomElement as defineBhTooltip } from "@actabldesign/bellhop-core/components/bh-tooltip.js";
import { BhTrendChart as BhTrendChartElement, defineCustomElement as defineBhTrendChart } from "@actabldesign/bellhop-core/components/bh-trend-chart.js";
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
export const BhAccordion = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-accordion',
        elementClass: BhAccordionElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhAccordionChange: 'bhAccordionChange' },
        defineCustomElement: defineBhAccordion
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-accordion',
        properties: {
            mode: 'mode',
            value: 'value',
            collapsible: 'collapsible'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAccordionItem = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-accordion-item',
        elementClass: BhAccordionItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhAccordionToggle: 'bhAccordionToggle',
            onBhAccordionClick: 'bhAccordionClick'
        },
        defineCustomElement: defineBhAccordionItem
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-accordion-item',
        properties: {
            value: 'value',
            header: 'header',
            expanded: 'expanded',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAppbar = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-appbar',
        elementClass: BhAppbarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhMenuToggle: 'bhMenuToggle',
            onBhBreadcrumbClick: 'bhBreadcrumbClick',
            onBhNotificationClick: 'bhNotificationClick',
            onBhCalendarClick: 'bhCalendarClick',
            onBhSettingsClick: 'bhSettingsClick'
        },
        defineCustomElement: defineBhAppbar
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-appbar',
        properties: {
            isMenuOpen: 'is-menu-open',
            logoSrc: 'logo-src',
            logoAlt: 'logo-alt',
            notificationCount: 'notification-count'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAutocompleteMenu = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-autocomplete-menu',
        elementClass: BhAutocompleteMenuElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhItemClick: 'bhItemClick',
            onBhItemHover: 'bhItemHover'
        },
        defineCustomElement: defineBhAutocompleteMenu
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-autocomplete-menu',
        properties: {
            visible: 'visible',
            selectedIndex: 'selected-index',
            maxHeight: 'max-height',
            multiSelect: 'multi-select',
            searchQuery: 'search-query'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAvatar = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-avatar',
        elementClass: BhAvatarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhMouseEnter: 'bhMouseEnter',
            onBhMouseLeave: 'bhMouseLeave'
        },
        defineCustomElement: defineBhAvatar
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-avatar',
        properties: {
            size: 'size',
            type: 'type',
            status: 'status',
            text: 'text',
            imageSrc: 'image-src',
            alt: 'alt'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAvatarAdd = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-avatar-add',
        elementClass: BhAvatarAddElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClick: 'bhClick' },
        defineCustomElement: defineBhAvatarAdd
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-avatar-add',
        properties: {
            size: 'size',
            disabled: 'disabled',
            showTooltip: 'show-tooltip',
            tooltipText: 'tooltip-text'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhAvatarStacked = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-avatar-stacked',
        elementClass: BhAvatarStackedElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhAvatarStacked
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-avatar-stacked',
        properties: {
            size: 'size',
            avatars: 'avatars',
            maxVisible: 'max-visible',
            showAddButton: 'show-add-button',
            addTooltipText: 'add-tooltip-text'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhBadge = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-badge',
        elementClass: BhBadgeElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhDismiss: 'bhDismiss' },
        defineCustomElement: defineBhBadge
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-badge',
        properties: {
            variant: 'variant',
            size: 'size',
            emphasis: 'emphasis',
            label: 'label',
            icon: 'icon',
            dismissible: 'dismissible',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhBadgeDot = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-badge-dot',
        elementClass: BhBadgeDotElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhBadgeDot
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-badge-dot',
        properties: {
            size: 'size',
            color: 'color',
            outline: 'outline'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhBarChart = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-bar-chart',
        elementClass: BhBarChartElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhBarChart
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-bar-chart',
        properties: {
            type: 'type',
            orientation: 'orientation',
            animated: 'animated',
            maxHeight: 'max-height',
            maxWidth: 'max-width'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhBreadcrumbs = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-breadcrumbs',
        elementClass: BhBreadcrumbsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhItemClick: 'bhItemClick',
            onBhNavigate: 'bhNavigate'
        },
        defineCustomElement: defineBhBreadcrumbs
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-breadcrumbs',
        properties: {
            items: 'items',
            separator: 'separator',
            showHome: 'show-home',
            maxVisibleItems: 'max-visible-items'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhButton = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-button',
        elementClass: BhButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClick: 'bhClick' },
        defineCustomElement: defineBhButton
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-button',
        properties: {
            hierarchy: 'hierarchy',
            kind: 'kind',
            icon: 'icon',
            size: 'size',
            label: 'label',
            iconName: 'icon-name',
            disabled: 'disabled',
            loading: 'loading',
            type: 'type'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhButtonIcon = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-button-icon',
        elementClass: BhButtonIconElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClick: 'bhClick' },
        defineCustomElement: defineBhButtonIcon
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-button-icon',
        properties: {
            hierarchy: 'hierarchy',
            size: 'size',
            iconName: 'icon-name',
            disabled: 'disabled',
            loading: 'loading',
            type: 'type',
            ariaLabel: 'aria-label'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCard = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-card',
        elementClass: BhCardElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhCard
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-card',
        properties: {
            showHeader: 'show-header',
            showFooter: 'show-footer',
            contentMinHeight: 'content-min-height',
            placeholderText: 'placeholder-text'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCardFooter = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-card-footer',
        elementClass: BhCardFooterElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhCardFooter
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-card-footer',
        properties: {
            showDivider: 'show-divider',
            alignment: 'alignment'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCardHeader = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-card-header',
        elementClass: BhCardHeaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhDropdownClick: 'bhDropdownClick' },
        defineCustomElement: defineBhCardHeader
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-card-header',
        properties: {
            showFeaturedIcon: 'show-featured-icon',
            featuredIcon: 'featured-icon',
            featuredIconStyle: 'featured-icon-style',
            featuredIconColor: 'featured-icon-color',
            showTitle: 'show-title',
            headerTitle: 'header-title',
            showBadge: 'show-badge',
            badgeText: 'badge-text',
            showSupportingText: 'show-supporting-text',
            supportingText: 'supporting-text',
            showDropdown: 'show-dropdown',
            showDivider: 'show-divider'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhChartTooltip = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-chart-tooltip',
        elementClass: BhChartTooltipElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhChartTooltip
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-chart-tooltip',
        properties: {
            visible: 'visible',
            x: 'x',
            y: 'y',
            header: 'header',
            total: 'total',
            showTotal: 'show-total',
            storybookMode: 'storybook-mode'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCheckbox = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-checkbox',
        elementClass: BhCheckboxElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhChange: 'bhChange' },
        defineCustomElement: defineBhCheckbox
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-checkbox',
        properties: {
            size: 'size',
            checked: 'checked',
            indeterminate: 'indeterminate',
            disabled: 'disabled',
            name: 'name',
            value: 'value',
            label: 'label',
            supportingText: 'supporting-text',
            required: 'required',
            defaultChecked: 'default-checked'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCheckboxGroup = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-checkbox-group',
        elementClass: BhCheckboxGroupElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhChange: 'bhChange' },
        defineCustomElement: defineBhCheckboxGroup
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-checkbox-group',
        properties: {
            type: 'type',
            name: 'name',
            value: 'value',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhCheckboxGroupItem = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-checkbox-group-item',
        elementClass: BhCheckboxGroupItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemChange: 'bhItemChange' },
        defineCustomElement: defineBhCheckboxGroupItem
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-checkbox-group-item',
        properties: {
            type: 'type',
            size: 'size',
            value: 'value',
            checked: 'checked',
            selected: 'selected',
            disabled: 'disabled',
            icon: 'icon',
            itemTitle: 'item-title',
            subtitle: 'subtitle',
            description: 'description',
            name: 'name'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhContainer = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-container',
        elementClass: BhContainerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhContainer
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-container',
        properties: { withFooter: 'with-footer' },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhContainerFooter = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-container-footer',
        elementClass: BhContainerFooterElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhButtonClick: 'bhButtonClick' },
        defineCustomElement: defineBhContainerFooter
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-container-footer',
        properties: {
            size: 'size',
            buttonLabel: 'button-label'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDataGrid = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-data-grid',
        elementClass: BhDataGridElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhSortChange: 'bhSortChange',
            onBhFilterChange: 'bhFilterChange',
            onBhSelectionChange: 'bhSelectionChange',
            onBhPageChange: 'bhPageChange',
            onBhRowClick: 'bhRowClick',
            onBhCellClick: 'bhCellClick',
            onBhExpandChange: 'bhExpandChange',
            onBhGroupToggle: 'bhGroupToggle',
            onBhEditStart: 'bhEditStart',
            onBhEditCancel: 'bhEditCancel',
            onBhEditSave: 'bhEditSave',
            onBhCellChange: 'bhCellChange',
            onBhValidationError: 'bhValidationError'
        },
        defineCustomElement: defineBhDataGrid
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-data-grid',
        properties: {
            size: 'size',
            striped: 'striped',
            bordered: 'bordered',
            stickyHeader: 'sticky-header',
            maxHeight: 'max-height',
            caption: 'caption',
            captionPosition: 'caption-position',
            emptyTitle: 'empty-title',
            emptyDescription: 'empty-description',
            loading: 'loading',
            loadingType: 'loading-type',
            skeletonRowCount: 'skeleton-row-count',
            enableSorting: 'enable-sorting',
            enableMultiSort: 'enable-multi-sort',
            enableFiltering: 'enable-filtering',
            enableGlobalFilter: 'enable-global-filter',
            showFilterRow: 'show-filter-row',
            globalFilterPlaceholder: 'global-filter-placeholder',
            globalFilter: 'global-filter',
            selectionMode: 'selection-mode',
            enablePagination: 'enable-pagination',
            page: 'page',
            pageSize: 'page-size',
            enableExpansion: 'enable-expansion',
            enableGrouping: 'enable-grouping',
            enableEditing: 'enable-editing',
            editMode: 'edit-mode',
            showEditActions: 'show-edit-actions'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDatePicker = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-date-picker',
        elementClass: BhDatePickerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhDateSelect: 'bhDateSelect'
        },
        defineCustomElement: defineBhDatePicker
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-date-picker',
        properties: {
            variant: 'variant',
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            label: 'label',
            placeholder: 'placeholder',
            inputWidth: 'input-width',
            showLabel: 'show-label',
            showFooter: 'show-footer',
            showOtherMonthDays: 'show-other-month-days'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDatePickerContent = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-date-picker-content',
        elementClass: BhDatePickerContentElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhDateSelect: 'bhDateSelect',
            onBhMonthChange: 'bhMonthChange',
            onBhMonthYearChange: 'bhMonthYearChange'
        },
        defineCustomElement: defineBhDatePickerContent
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-date-picker-content',
        properties: {
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            initialMonth: 'initial-month',
            initialYear: 'initial-year',
            displayMonth: 'display-month',
            displayYear: 'display-year',
            showOtherMonthDays: 'show-other-month-days'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDateRangePicker = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-date-range-picker',
        elementClass: BhDateRangePickerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhDateRangeSelect: 'bhDateRangeSelect'
        },
        defineCustomElement: defineBhDateRangePicker
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-date-range-picker',
        properties: {
            variant: 'variant',
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            startLabel: 'start-label',
            endLabel: 'end-label',
            startPlaceholder: 'start-placeholder',
            endPlaceholder: 'end-placeholder',
            inputWidth: 'input-width',
            showLabel: 'show-label',
            showFooter: 'show-footer',
            showOtherMonthDays: 'show-other-month-days'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDateRangePickerContent = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-date-range-picker-content',
        elementClass: BhDateRangePickerContentElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhDateRangeSelect: 'bhDateRangeSelect'
        },
        defineCustomElement: defineBhDateRangePickerContent
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-date-range-picker-content',
        properties: {
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            showOtherMonthDays: 'show-other-month-days'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDropdown = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-dropdown',
        elementClass: BhDropdownElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemClick: 'bhItemClick' },
        defineCustomElement: defineBhDropdown
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-dropdown',
        properties: {
            size: 'size',
            state: 'state',
            variant: 'variant',
            label: 'label',
            iconName: 'icon-name',
            disabled: 'disabled',
            menuItems: 'menu-items',
            header: 'header',
            avatarSrc: 'avatar-src',
            avatarAlt: 'avatar-alt',
            avatarSize: 'avatar-size',
            avatarName: 'avatar-name',
            avatarEmail: 'avatar-email',
            showIcons: 'show-icons'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhDropdownMenu = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-dropdown-menu',
        elementClass: BhDropdownMenuElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemClick: 'bhItemClick' },
        defineCustomElement: defineBhDropdownMenu
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-dropdown-menu',
        properties: {
            header: 'header',
            menuItems: 'menu-items',
            visible: 'visible',
            showIcons: 'show-icons',
            scrollable: 'scrollable'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhEmptyState = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-empty-state',
        elementClass: BhEmptyStateElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhPrimaryAction: 'bhPrimaryAction',
            onBhSecondaryAction: 'bhSecondaryAction'
        },
        defineCustomElement: defineBhEmptyState
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-empty-state',
        properties: {
            emptyTitle: 'empty-title',
            description: 'description',
            illustrationSize: 'illustration-size',
            illustrationPath: 'illustration-path',
            primaryActionText: 'primary-action-text',
            primaryActionIcon: 'primary-action-icon',
            secondaryActionText: 'secondary-action-text',
            secondaryActionIcon: 'secondary-action-icon',
            maxWidth: 'max-width'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhFeaturedIcon = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-featured-icon',
        elementClass: BhFeaturedIconElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhFeaturedIcon
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-featured-icon',
        properties: {
            size: 'size',
            color: 'color',
            iconStyle: 'icon-style',
            icon: 'icon'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhIllustrations = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-illustrations',
        elementClass: BhIllustrationsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhIllustrations
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-illustrations',
        properties: {
            size: 'size',
            illustrationTitle: 'illustration-title',
            description: 'description',
            svgPath: 'svg-path',
            alt: 'alt'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhInputAutocomplete = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-input-autocomplete',
        elementClass: BhInputAutocompleteElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhSelectedItemsChange: 'bhSelectedItemsChange',
            onBhFocus: 'bhFocus',
            onBhBlur: 'bhBlur',
            onBhHelpClick: 'bhHelpClick',
            onBhOptionSelect: 'bhOptionSelect'
        },
        defineCustomElement: defineBhInputAutocomplete
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-input-autocomplete',
        properties: {
            state: 'state',
            error: 'error',
            required: 'required',
            disabled: 'disabled',
            showHelpIcon: 'show-help-icon',
            showLeadingIcon: 'show-leading-icon',
            showLabel: 'show-label',
            showHintText: 'show-hint-text',
            label: 'label',
            placeholder: 'placeholder',
            hintText: 'hint-text',
            leadingIcon: 'leading-icon',
            helpIconTooltip: 'help-icon-tooltip',
            value: 'value',
            width: 'width',
            maxOptions: 'max-options',
            multiSelect: 'multi-select',
            minSearchLength: 'min-search-length'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhInputNumber = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-input-number',
        elementClass: BhInputNumberElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhFocus: 'bhFocus',
            onBhBlur: 'bhBlur',
            onBhHelpClick: 'bhHelpClick'
        },
        defineCustomElement: defineBhInputNumber
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-input-number',
        properties: {
            error: 'error',
            required: 'required',
            disabled: 'disabled',
            showHelpIcon: 'show-help-icon',
            showLeadingIcon: 'show-leading-icon',
            showLabel: 'show-label',
            showHintText: 'show-hint-text',
            label: 'label',
            placeholder: 'placeholder',
            hintText: 'hint-text',
            leadingIcon: 'leading-icon',
            helpIconTooltip: 'help-icon-tooltip',
            value: 'value',
            min: 'min',
            max: 'max',
            step: 'step',
            prefixText: 'prefix-text',
            suffixText: 'suffix-text',
            width: 'width',
            name: 'name',
            defaultValue: 'default-value',
            validationMessage: 'validation-message'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhInputPassword = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-input-password',
        elementClass: BhInputPasswordElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhInput: 'bhInput',
            onBhFocus: 'bhFocus',
            onBhBlur: 'bhBlur',
            onBhHelpClick: 'bhHelpClick',
            onBhVisibilityToggle: 'bhVisibilityToggle'
        },
        defineCustomElement: defineBhInputPassword
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-input-password',
        properties: {
            label: 'label',
            placeholder: 'placeholder',
            hintText: 'hint-text',
            showLabel: 'show-label',
            showHintText: 'show-hint-text',
            showHelpIcon: 'show-help-icon',
            showLeadingIcon: 'show-leading-icon',
            error: 'error',
            disabled: 'disabled',
            required: 'required',
            helpIconTooltip: 'help-icon-tooltip',
            leadingIcon: 'leading-icon',
            value: 'value',
            name: 'name',
            defaultValue: 'default-value',
            validationMessage: 'validation-message'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhInputText = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-input-text',
        elementClass: BhInputTextElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhInput: 'bhInput',
            onBhFocus: 'bhFocus',
            onBhBlur: 'bhBlur',
            onBhHelpClick: 'bhHelpClick'
        },
        defineCustomElement: defineBhInputText
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-input-text',
        properties: {
            label: 'label',
            placeholder: 'placeholder',
            hintText: 'hint-text',
            showLabel: 'show-label',
            showHintText: 'show-hint-text',
            showHelpIcon: 'show-help-icon',
            showLeadingIcon: 'show-leading-icon',
            showTrailingIcon: 'show-trailing-icon',
            error: 'error',
            disabled: 'disabled',
            required: 'required',
            helpIconTooltip: 'help-icon-tooltip',
            leadingIcon: 'leading-icon',
            trailingIcon: 'trailing-icon',
            value: 'value',
            name: 'name',
            defaultValue: 'default-value',
            validationMessage: 'validation-message',
            type: 'type',
            width: 'width',
            readOnly: 'read-only',
            state: 'state'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhInputVerification = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-input-verification',
        elementClass: BhInputVerificationElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhComplete: 'bhComplete'
        },
        defineCustomElement: defineBhInputVerification
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-input-verification',
        properties: {
            size: 'size',
            digits: 'digits',
            label: 'label',
            showLabel: 'show-label',
            hintText: 'hint-text',
            showHintText: 'show-hint-text',
            error: 'error',
            disabled: 'disabled',
            required: 'required',
            showSeparator: 'show-separator',
            placeholder: 'placeholder',
            width: 'width',
            value: 'value'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhLabel = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-label',
        elementClass: BhLabelElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhHelpClick: 'bhHelpClick' },
        defineCustomElement: defineBhLabel
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-label',
        properties: {
            label: 'label',
            layout: 'layout',
            for: 'for',
            supportingText: 'supporting-text',
            required: 'required',
            showHelpIcon: 'show-help-icon',
            helpIconTooltip: 'help-icon-tooltip',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhLoaderSpinner = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-loader-spinner',
        elementClass: BhLoaderSpinnerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhLoaderSpinner
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-loader-spinner',
        properties: {
            size: 'size',
            variant: 'variant',
            overlay: 'overlay',
            overlayMessage: 'overlay-message',
            showMessage: 'show-message',
            message: 'message'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhLogoBox = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-logo-box',
        elementClass: BhLogoBoxElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhProductSelect: 'bhProductSelect' },
        defineCustomElement: defineBhLogoBox
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-logo-box',
        properties: {
            logoType: 'logo-type',
            logoSrc: 'logo-src',
            assetBasePath: 'asset-base-path'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhModal = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-modal',
        elementClass: BhModalElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClose: 'bhClose' },
        defineCustomElement: defineBhModal
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-modal',
        properties: {
            visible: 'visible',
            overlay: 'overlay',
            width: 'width'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhModalActions = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-modal-actions',
        elementClass: BhModalActionsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhPrimaryAction: 'bhPrimaryAction',
            onBhSecondaryAction: 'bhSecondaryAction'
        },
        defineCustomElement: defineBhModalActions
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-modal-actions',
        properties: {
            type: 'type',
            destructive: 'destructive',
            primaryLabel: 'primary-label',
            secondaryLabel: 'secondary-label',
            divider: 'divider'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhModalHeader = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-modal-header',
        elementClass: BhModalHeaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClose: 'bhClose' },
        defineCustomElement: defineBhModalHeader
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-modal-header',
        properties: {
            modalTitle: 'modal-title',
            description: 'description',
            icon: 'icon',
            iconColor: 'icon-color',
            showIcon: 'show-icon',
            showCloseButton: 'show-close-button',
            type: 'type',
            paddingBottom: 'padding-bottom',
            divider: 'divider'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhMonthPicker = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-month-picker',
        elementClass: BhMonthPickerElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhMonthYearSelect: 'bhMonthYearSelect'
        },
        defineCustomElement: defineBhMonthPicker
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-month-picker',
        properties: {
            variant: 'variant',
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            label: 'label',
            placeholder: 'placeholder',
            inputWidth: 'input-width',
            showLabel: 'show-label',
            showFooter: 'show-footer'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhMonthPickerContent = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-month-picker-content',
        elementClass: BhMonthPickerContentElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhMonthYearSelect: 'bhMonthYearSelect'
        },
        defineCustomElement: defineBhMonthPickerContent
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-month-picker-content',
        properties: {
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            scrollable: 'scrollable',
            selectedMonth: 'selected-month',
            selectedYear: 'selected-year',
            height: 'height'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhNavItem = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-nav-item',
        elementClass: BhNavItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhClick: 'bhClick' },
        defineCustomElement: defineBhNavItem
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-nav-item',
        properties: {
            icon: 'icon',
            label: 'label',
            isActive: 'is-active',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhNotification = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-notification',
        elementClass: BhNotificationElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhAction: 'bhAction',
            onBhDismiss: 'bhDismiss',
            onBhClose: 'bhClose'
        },
        defineCustomElement: defineBhNotification
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-notification',
        properties: {
            type: 'type',
            notificationTitle: 'notification-title',
            description: 'description',
            actionText: 'action-text',
            dismissText: 'dismiss-text',
            dismissible: 'dismissible',
            icon: 'icon'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPageNavigation = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-page-navigation',
        elementClass: BhPageNavigationElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemClick: 'bhItemClick' },
        defineCustomElement: defineBhPageNavigation
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-page-navigation',
        properties: { navTitle: 'nav-title' },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPageNavigationChild = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-page-navigation-child',
        elementClass: BhPageNavigationChildElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemClick: 'bhItemClick' },
        defineCustomElement: defineBhPageNavigationChild
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-page-navigation-child',
        properties: {
            label: 'label',
            badge: 'badge',
            showBadge: 'show-badge',
            isActive: 'is-active'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPageNavigationMultiLevel = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-page-navigation-multi-level',
        elementClass: BhPageNavigationMultiLevelElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhToggle: 'bhToggle',
            onBhChildClick: 'bhChildClick',
            onBhAddClick: 'bhAddClick'
        },
        defineCustomElement: defineBhPageNavigationMultiLevel
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-page-navigation-multi-level',
        properties: {
            label: 'label',
            icon: 'icon',
            badge: 'badge',
            isExpanded: 'is-expanded'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPageNavigationSingleLevel = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-page-navigation-single-level',
        elementClass: BhPageNavigationSingleLevelElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhItemClick: 'bhItemClick' },
        defineCustomElement: defineBhPageNavigationSingleLevel
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-page-navigation-single-level',
        properties: {
            label: 'label',
            icon: 'icon',
            isActive: 'is-active'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPagination = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-pagination',
        elementClass: BhPaginationElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhPageChange: 'bhPageChange',
            onBhPageSizeChange: 'bhPageSizeChange'
        },
        defineCustomElement: defineBhPagination
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-pagination',
        properties: {
            page: 'page',
            totalItems: 'total-items',
            pageSize: 'page-size',
            showPageSizeSelector: 'show-page-size-selector',
            showItemCount: 'show-item-count',
            showFirstLastButtons: 'show-first-last-buttons',
            size: 'size',
            disabled: 'disabled',
            rowsPerPageLabel: 'rows-per-page-label',
            showingResultsLabel: 'showing-results-label',
            pageInfoLabel: 'page-info-label'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPickerMenu = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-picker-menu',
        elementClass: BhPickerMenuElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhChange: 'bhChange',
            onBhMonthYearSelect: 'bhMonthYearSelect',
            onBhCancel: 'bhCancel',
            onBhApply: 'bhApply',
            onBhToday: 'bhToday'
        },
        defineCustomElement: defineBhPickerMenu
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-picker-menu',
        properties: {
            minYear: 'min-year',
            maxYear: 'max-year',
            disabled: 'disabled',
            animationClass: 'animation-class',
            visible: 'visible',
            showFooter: 'show-footer',
            showTodayButton: 'show-today-button',
            disableApply: 'disable-apply'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPieChart = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-pie-chart',
        elementClass: BhPieChartElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhPieChart
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-pie-chart',
        properties: {
            hole: 'hole',
            size: 'size',
            animated: 'animated',
            gap: 'gap'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPopover = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-popover',
        elementClass: BhPopoverElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhItemSelect: 'bhItemSelect',
            onBhPortfolioClick: 'bhPortfolioClick',
            onBhSearchChange: 'bhSearchChange'
        },
        defineCustomElement: defineBhPopover
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-popover',
        properties: {
            popoverTitle: 'popover-title',
            viewPortfolioText: 'view-portfolio-text',
            searchPlaceholder: 'search-placeholder',
            width: 'width',
            showSearch: 'show-search',
            showAvatar: 'show-avatar',
            avatarSrc: 'avatar-src',
            items: 'items'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhProductSwitcher = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-product-switcher',
        elementClass: BhProductSwitcherElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhClose: 'bhClose',
            onBhProductSelect: 'bhProductSelect'
        },
        defineCustomElement: defineBhProductSwitcher
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-product-switcher',
        properties: { isOpen: 'is-open' },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhPropertySwitcher = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-property-switcher',
        elementClass: BhPropertySwitcherElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhPropertyChange: 'bhPropertyChange' },
        defineCustomElement: defineBhPropertySwitcher
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-property-switcher',
        properties: {
            selectedProperty: 'selected-property',
            grouped: 'grouped',
            searchPlaceholder: 'search-placeholder'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhRadioButton = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-radio-button',
        elementClass: BhRadioButtonElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhChange: 'bhChange' },
        defineCustomElement: defineBhRadioButton
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-radio-button',
        properties: {
            size: 'size',
            selected: 'selected',
            disabled: 'disabled',
            value: 'value',
            name: 'name',
            label: 'label',
            supportingText: 'supporting-text'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhSidebar = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-sidebar',
        elementClass: BhSidebarElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhMenuItemClick: 'bhMenuItemClick',
            onBhSearchClick: 'bhSearchClick',
            onBhAvatarMenuClick: 'bhAvatarMenuClick'
        },
        defineCustomElement: defineBhSidebar
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-sidebar',
        properties: {
            logoType: 'logo-type',
            avatarUrl: 'avatar-url',
            avatarInitials: 'avatar-initials',
            avatarName: 'avatar-name',
            avatarEmail: 'avatar-email',
            collapsed: 'collapsed'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhSkeletonLoader = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-skeleton-loader',
        elementClass: BhSkeletonLoaderElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhSkeletonLoader
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-skeleton-loader',
        properties: {
            width: 'width',
            height: 'height',
            circle: 'circle'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTabItem = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-tab-item',
        elementClass: BhTabItemElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhTabItemClick: 'bhTabItemClick' },
        defineCustomElement: defineBhTabItem
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-tab-item',
        properties: {
            value: 'value',
            label: 'label',
            active: 'active',
            disabled: 'disabled'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTabs = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-tabs',
        elementClass: BhTabsElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhTabChange: 'bhTabChange' },
        defineCustomElement: defineBhTabs
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-tabs',
        properties: {
            type: 'type',
            orientation: 'orientation',
            fullWidth: 'full-width',
            value: 'value'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTag = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-tag',
        elementClass: BhTagElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhDismiss: 'bhDismiss' },
        defineCustomElement: defineBhTag
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-tag',
        properties: {
            variant: 'variant',
            size: 'size',
            label: 'label',
            dismissible: 'dismissible',
            disabled: 'disabled',
            maxWidth: 'max-width',
            avatarSrc: 'avatar-src'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTextarea = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-textarea',
        elementClass: BhTextareaElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {
            onBhInput: 'bhInput',
            onBhFocus: 'bhFocus',
            onBhBlur: 'bhBlur',
            onBhHelpClick: 'bhHelpClick'
        },
        defineCustomElement: defineBhTextarea
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-textarea',
        properties: {
            label: 'label',
            placeholder: 'placeholder',
            hintText: 'hint-text',
            showLabel: 'show-label',
            showHintText: 'show-hint-text',
            showHelpIcon: 'show-help-icon',
            error: 'error',
            disabled: 'disabled',
            required: 'required',
            helpIconTooltip: 'help-icon-tooltip',
            value: 'value',
            name: 'name',
            defaultValue: 'default-value',
            validationMessage: 'validation-message',
            rows: 'rows',
            resize: 'resize',
            maxLength: 'max-length'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhToggle = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-toggle',
        elementClass: BhToggleElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: { onBhChange: 'bhChange' },
        defineCustomElement: defineBhToggle
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-toggle',
        properties: {
            size: 'size',
            showText: 'show-text',
            label: 'label',
            supportingText: 'supporting-text',
            disabled: 'disabled',
            checked: 'checked',
            name: 'name',
            value: 'value',
            required: 'required',
            defaultChecked: 'default-checked'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTooltip = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-tooltip',
        elementClass: BhTooltipElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhTooltip
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-tooltip',
        properties: {
            text: 'text',
            position: 'position',
            variant: 'variant',
            visible: 'visible',
            maxWidth: 'max-width'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
export const BhTrendChart = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent({
        tagName: 'bh-trend-chart',
        elementClass: BhTrendChartElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {},
        defineCustomElement: defineBhTrendChart
    })
    : /*@__PURE__*/ createSSRComponent({
        tagName: 'bh-trend-chart',
        properties: {
            trend: 'trend',
            animated: 'animated',
            variant: 'variant',
            width: 'width',
            height: 'height'
        },
        hydrateModule: import('@actabldesign/bellhop-core/hydrate')
    });
