/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */
import { type AutocompleteMenuItem, type BhAppbarCustomEvent, type BhAutocompleteMenuCustomEvent, type BhAvatarAddCustomEvent, type BhBreadcrumbsCustomEvent, type BhButtonCustomEvent, type BhButtonIconCustomEvent, type BhDataGridCustomEvent, type BhDatePickerContentCustomEvent, type BhDatePickerCustomEvent, type BhDateRangePickerContentCustomEvent, type BhDateRangePickerCustomEvent, type BhDropdownCustomEvent, type BhDropdownMenuCustomEvent, type BhInputAutocompleteCustomEvent, type BhLogoBoxCustomEvent, type BhMonthPickerContentCustomEvent, type BhMonthPickerCustomEvent, type BhPaginationCustomEvent, type BhPickerMenuCustomEvent, type BhPopoverCustomEvent, type BhProduct, type BhProductSwitcherCustomEvent, type BhPropertySwitcherCustomEvent, type BhSidebarCustomEvent, type BreadcrumbItem, type DataGridCellChangeEvent, type DataGridCellClickEvent, type DataGridEditCancelEvent, type DataGridEditSaveEvent, type DataGridEditStartEvent, type DataGridExpandChangeEvent, type DataGridFilterChangeEvent, type DataGridGroupToggleEvent, type DataGridPageChangeEvent, type DataGridRowClickEvent, type DataGridSelectionChangeEvent, type DataGridSortChangeEvent, type DataGridValidationErrorEvent, type DropdownMenuItem, type MonthYear, type PaginationChangeEvent, type PopoverItem, type PropertyOption, type SelectedDate, type SelectedDateRange } from "@actabldesign/bellhop-core";
import { BhAccordionItem as BhAccordionItemElement } from "@actabldesign/bellhop-core/components/bh-accordion-item.js";
import { BhAccordion as BhAccordionElement } from "@actabldesign/bellhop-core/components/bh-accordion.js";
import { BhAppbar as BhAppbarElement } from "@actabldesign/bellhop-core/components/bh-appbar.js";
import { BhAutocompleteMenu as BhAutocompleteMenuElement } from "@actabldesign/bellhop-core/components/bh-autocomplete-menu.js";
import { BhAvatarAdd as BhAvatarAddElement } from "@actabldesign/bellhop-core/components/bh-avatar-add.js";
import { BhAvatarStacked as BhAvatarStackedElement } from "@actabldesign/bellhop-core/components/bh-avatar-stacked.js";
import { BhAvatar as BhAvatarElement } from "@actabldesign/bellhop-core/components/bh-avatar.js";
import { BhBadgeDot as BhBadgeDotElement } from "@actabldesign/bellhop-core/components/bh-badge-dot.js";
import { BhBadge as BhBadgeElement } from "@actabldesign/bellhop-core/components/bh-badge.js";
import { BhBarChart as BhBarChartElement } from "@actabldesign/bellhop-core/components/bh-bar-chart.js";
import { BhBreadcrumbs as BhBreadcrumbsElement } from "@actabldesign/bellhop-core/components/bh-breadcrumbs.js";
import { BhButtonIcon as BhButtonIconElement } from "@actabldesign/bellhop-core/components/bh-button-icon.js";
import { BhButton as BhButtonElement } from "@actabldesign/bellhop-core/components/bh-button.js";
import { BhCardFooter as BhCardFooterElement } from "@actabldesign/bellhop-core/components/bh-card-footer.js";
import { BhCardHeader as BhCardHeaderElement } from "@actabldesign/bellhop-core/components/bh-card-header.js";
import { BhCard as BhCardElement } from "@actabldesign/bellhop-core/components/bh-card.js";
import { BhChartTooltip as BhChartTooltipElement } from "@actabldesign/bellhop-core/components/bh-chart-tooltip.js";
import { BhCheckboxGroupItem as BhCheckboxGroupItemElement } from "@actabldesign/bellhop-core/components/bh-checkbox-group-item.js";
import { BhCheckboxGroup as BhCheckboxGroupElement } from "@actabldesign/bellhop-core/components/bh-checkbox-group.js";
import { BhCheckbox as BhCheckboxElement } from "@actabldesign/bellhop-core/components/bh-checkbox.js";
import { BhContainerFooter as BhContainerFooterElement } from "@actabldesign/bellhop-core/components/bh-container-footer.js";
import { BhContainer as BhContainerElement } from "@actabldesign/bellhop-core/components/bh-container.js";
import { BhDataGrid as BhDataGridElement } from "@actabldesign/bellhop-core/components/bh-data-grid.js";
import { BhDatePickerContent as BhDatePickerContentElement } from "@actabldesign/bellhop-core/components/bh-date-picker-content.js";
import { BhDatePicker as BhDatePickerElement } from "@actabldesign/bellhop-core/components/bh-date-picker.js";
import { BhDateRangePickerContent as BhDateRangePickerContentElement } from "@actabldesign/bellhop-core/components/bh-date-range-picker-content.js";
import { BhDateRangePicker as BhDateRangePickerElement } from "@actabldesign/bellhop-core/components/bh-date-range-picker.js";
import { BhDropdownMenu as BhDropdownMenuElement } from "@actabldesign/bellhop-core/components/bh-dropdown-menu.js";
import { BhDropdown as BhDropdownElement } from "@actabldesign/bellhop-core/components/bh-dropdown.js";
import { BhEmptyState as BhEmptyStateElement } from "@actabldesign/bellhop-core/components/bh-empty-state.js";
import { BhFeaturedIcon as BhFeaturedIconElement } from "@actabldesign/bellhop-core/components/bh-featured-icon.js";
import { BhIllustrations as BhIllustrationsElement } from "@actabldesign/bellhop-core/components/bh-illustrations.js";
import { BhInputAutocomplete as BhInputAutocompleteElement } from "@actabldesign/bellhop-core/components/bh-input-autocomplete.js";
import { BhInputNumber as BhInputNumberElement } from "@actabldesign/bellhop-core/components/bh-input-number.js";
import { BhInputPassword as BhInputPasswordElement } from "@actabldesign/bellhop-core/components/bh-input-password.js";
import { BhInputText as BhInputTextElement } from "@actabldesign/bellhop-core/components/bh-input-text.js";
import { BhInputVerification as BhInputVerificationElement } from "@actabldesign/bellhop-core/components/bh-input-verification.js";
import { BhLabel as BhLabelElement } from "@actabldesign/bellhop-core/components/bh-label.js";
import { BhLoaderSpinner as BhLoaderSpinnerElement } from "@actabldesign/bellhop-core/components/bh-loader-spinner.js";
import { BhLogoBox as BhLogoBoxElement } from "@actabldesign/bellhop-core/components/bh-logo-box.js";
import { BhModalActions as BhModalActionsElement } from "@actabldesign/bellhop-core/components/bh-modal-actions.js";
import { BhModalHeader as BhModalHeaderElement } from "@actabldesign/bellhop-core/components/bh-modal-header.js";
import { BhModal as BhModalElement } from "@actabldesign/bellhop-core/components/bh-modal.js";
import { BhMonthPickerContent as BhMonthPickerContentElement } from "@actabldesign/bellhop-core/components/bh-month-picker-content.js";
import { BhMonthPicker as BhMonthPickerElement } from "@actabldesign/bellhop-core/components/bh-month-picker.js";
import { BhNavItem as BhNavItemElement } from "@actabldesign/bellhop-core/components/bh-nav-item.js";
import { BhNotification as BhNotificationElement } from "@actabldesign/bellhop-core/components/bh-notification.js";
import { BhPageNavigationChild as BhPageNavigationChildElement } from "@actabldesign/bellhop-core/components/bh-page-navigation-child.js";
import { BhPageNavigationMultiLevel as BhPageNavigationMultiLevelElement } from "@actabldesign/bellhop-core/components/bh-page-navigation-multi-level.js";
import { BhPageNavigationSingleLevel as BhPageNavigationSingleLevelElement } from "@actabldesign/bellhop-core/components/bh-page-navigation-single-level.js";
import { BhPageNavigation as BhPageNavigationElement } from "@actabldesign/bellhop-core/components/bh-page-navigation.js";
import { BhPagination as BhPaginationElement } from "@actabldesign/bellhop-core/components/bh-pagination.js";
import { BhPickerMenu as BhPickerMenuElement } from "@actabldesign/bellhop-core/components/bh-picker-menu.js";
import { BhPieChart as BhPieChartElement } from "@actabldesign/bellhop-core/components/bh-pie-chart.js";
import { BhPopover as BhPopoverElement } from "@actabldesign/bellhop-core/components/bh-popover.js";
import { BhProductSwitcher as BhProductSwitcherElement } from "@actabldesign/bellhop-core/components/bh-product-switcher.js";
import { BhPropertySwitcher as BhPropertySwitcherElement } from "@actabldesign/bellhop-core/components/bh-property-switcher.js";
import { BhRadioButton as BhRadioButtonElement } from "@actabldesign/bellhop-core/components/bh-radio-button.js";
import { BhSidebar as BhSidebarElement } from "@actabldesign/bellhop-core/components/bh-sidebar.js";
import { BhSkeletonLoader as BhSkeletonLoaderElement } from "@actabldesign/bellhop-core/components/bh-skeleton-loader.js";
import { BhTabItem as BhTabItemElement } from "@actabldesign/bellhop-core/components/bh-tab-item.js";
import { BhTabs as BhTabsElement } from "@actabldesign/bellhop-core/components/bh-tabs.js";
import { BhTag as BhTagElement } from "@actabldesign/bellhop-core/components/bh-tag.js";
import { BhTextarea as BhTextareaElement } from "@actabldesign/bellhop-core/components/bh-textarea.js";
import { BhToggle as BhToggleElement } from "@actabldesign/bellhop-core/components/bh-toggle.js";
import { BhTooltip as BhTooltipElement } from "@actabldesign/bellhop-core/components/bh-tooltip.js";
import { BhTrendChart as BhTrendChartElement } from "@actabldesign/bellhop-core/components/bh-trend-chart.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
type BhAccordionEvents = {
    onBhAccordionChange: EventName<CustomEvent<string | string[]>>;
};
export declare const BhAccordion: StencilReactComponent<BhAccordionElement, BhAccordionEvents>;
type BhAccordionItemEvents = {
    onBhAccordionToggle: EventName<CustomEvent<{
        value: string;
        expanded: boolean;
    }>>;
    onBhAccordionClick: EventName<CustomEvent<string>>;
};
export declare const BhAccordionItem: StencilReactComponent<BhAccordionItemElement, BhAccordionItemEvents>;
type BhAppbarEvents = {
    onBhMenuToggle: EventName<CustomEvent<void>>;
    onBhBreadcrumbClick: EventName<BhAppbarCustomEvent<BreadcrumbItem>>;
    onBhNotificationClick: EventName<CustomEvent<void>>;
    onBhCalendarClick: EventName<CustomEvent<void>>;
    onBhSettingsClick: EventName<CustomEvent<void>>;
};
export declare const BhAppbar: StencilReactComponent<BhAppbarElement, BhAppbarEvents>;
type BhAutocompleteMenuEvents = {
    onBhItemClick: EventName<BhAutocompleteMenuCustomEvent<AutocompleteMenuItem>>;
    onBhItemHover: EventName<CustomEvent<number>>;
};
export declare const BhAutocompleteMenu: StencilReactComponent<BhAutocompleteMenuElement, BhAutocompleteMenuEvents>;
type BhAvatarEvents = {
    onBhMouseEnter: EventName<CustomEvent<void>>;
    onBhMouseLeave: EventName<CustomEvent<void>>;
};
export declare const BhAvatar: StencilReactComponent<BhAvatarElement, BhAvatarEvents>;
type BhAvatarAddEvents = {
    onBhClick: EventName<BhAvatarAddCustomEvent<MouseEvent>>;
};
export declare const BhAvatarAdd: StencilReactComponent<BhAvatarAddElement, BhAvatarAddEvents>;
type BhAvatarStackedEvents = NonNullable<unknown>;
export declare const BhAvatarStacked: StencilReactComponent<BhAvatarStackedElement, BhAvatarStackedEvents>;
type BhBadgeEvents = {
    onBhDismiss: EventName<CustomEvent<void>>;
};
export declare const BhBadge: StencilReactComponent<BhBadgeElement, BhBadgeEvents>;
type BhBadgeDotEvents = NonNullable<unknown>;
export declare const BhBadgeDot: StencilReactComponent<BhBadgeDotElement, BhBadgeDotEvents>;
type BhBarChartEvents = NonNullable<unknown>;
export declare const BhBarChart: StencilReactComponent<BhBarChartElement, BhBarChartEvents>;
type BhBreadcrumbsEvents = {
    onBhItemClick: EventName<BhBreadcrumbsCustomEvent<BreadcrumbItem>>;
    onBhNavigate: EventName<CustomEvent<string>>;
};
export declare const BhBreadcrumbs: StencilReactComponent<BhBreadcrumbsElement, BhBreadcrumbsEvents>;
type BhButtonEvents = {
    onBhClick: EventName<BhButtonCustomEvent<MouseEvent>>;
};
export declare const BhButton: StencilReactComponent<BhButtonElement, BhButtonEvents>;
type BhButtonIconEvents = {
    onBhClick: EventName<BhButtonIconCustomEvent<MouseEvent>>;
};
export declare const BhButtonIcon: StencilReactComponent<BhButtonIconElement, BhButtonIconEvents>;
type BhCardEvents = NonNullable<unknown>;
export declare const BhCard: StencilReactComponent<BhCardElement, BhCardEvents>;
type BhCardFooterEvents = NonNullable<unknown>;
export declare const BhCardFooter: StencilReactComponent<BhCardFooterElement, BhCardFooterEvents>;
type BhCardHeaderEvents = {
    onBhDropdownClick: EventName<CustomEvent<void>>;
};
export declare const BhCardHeader: StencilReactComponent<BhCardHeaderElement, BhCardHeaderEvents>;
type BhChartTooltipEvents = NonNullable<unknown>;
export declare const BhChartTooltip: StencilReactComponent<BhChartTooltipElement, BhChartTooltipEvents>;
type BhCheckboxEvents = {
    onBhChange: EventName<CustomEvent<boolean>>;
};
export declare const BhCheckbox: StencilReactComponent<BhCheckboxElement, BhCheckboxEvents>;
type BhCheckboxGroupEvents = {
    onBhChange: EventName<CustomEvent<string | string[]>>;
};
export declare const BhCheckboxGroup: StencilReactComponent<BhCheckboxGroupElement, BhCheckboxGroupEvents>;
type BhCheckboxGroupItemEvents = {
    onBhItemChange: EventName<CustomEvent<{
        value: string;
        checked: boolean;
    }>>;
};
export declare const BhCheckboxGroupItem: StencilReactComponent<BhCheckboxGroupItemElement, BhCheckboxGroupItemEvents>;
type BhContainerEvents = NonNullable<unknown>;
export declare const BhContainer: StencilReactComponent<BhContainerElement, BhContainerEvents>;
type BhContainerFooterEvents = {
    onBhButtonClick: EventName<CustomEvent<void>>;
};
export declare const BhContainerFooter: StencilReactComponent<BhContainerFooterElement, BhContainerFooterEvents>;
type BhDataGridEvents = {
    onBhSortChange: EventName<BhDataGridCustomEvent<DataGridSortChangeEvent>>;
    onBhFilterChange: EventName<BhDataGridCustomEvent<DataGridFilterChangeEvent>>;
    onBhSelectionChange: EventName<BhDataGridCustomEvent<DataGridSelectionChangeEvent>>;
    onBhPageChange: EventName<BhDataGridCustomEvent<DataGridPageChangeEvent>>;
    onBhRowClick: EventName<BhDataGridCustomEvent<DataGridRowClickEvent>>;
    onBhCellClick: EventName<BhDataGridCustomEvent<DataGridCellClickEvent>>;
    onBhExpandChange: EventName<BhDataGridCustomEvent<DataGridExpandChangeEvent>>;
    onBhGroupToggle: EventName<BhDataGridCustomEvent<DataGridGroupToggleEvent>>;
    onBhEditStart: EventName<BhDataGridCustomEvent<DataGridEditStartEvent>>;
    onBhEditCancel: EventName<BhDataGridCustomEvent<DataGridEditCancelEvent>>;
    onBhEditSave: EventName<BhDataGridCustomEvent<DataGridEditSaveEvent>>;
    onBhCellChange: EventName<BhDataGridCustomEvent<DataGridCellChangeEvent>>;
    onBhValidationError: EventName<BhDataGridCustomEvent<DataGridValidationErrorEvent>>;
};
export declare const BhDataGrid: StencilReactComponent<BhDataGridElement, BhDataGridEvents>;
type BhDatePickerEvents = {
    onBhChange: EventName<BhDatePickerCustomEvent<SelectedDate | null>>;
    onBhDateSelect: EventName<BhDatePickerCustomEvent<SelectedDate | null>>;
};
export declare const BhDatePicker: StencilReactComponent<BhDatePickerElement, BhDatePickerEvents>;
type BhDatePickerContentEvents = {
    onBhChange: EventName<BhDatePickerContentCustomEvent<SelectedDate | null>>;
    onBhDateSelect: EventName<BhDatePickerContentCustomEvent<SelectedDate | null>>;
    onBhMonthChange: EventName<CustomEvent<{
        month: number;
        year: number;
    }>>;
    onBhMonthYearChange: EventName<CustomEvent<{
        month: number;
        year: number;
    }>>;
};
export declare const BhDatePickerContent: StencilReactComponent<BhDatePickerContentElement, BhDatePickerContentEvents>;
type BhDateRangePickerEvents = {
    onBhChange: EventName<BhDateRangePickerCustomEvent<SelectedDateRange | null>>;
    onBhDateRangeSelect: EventName<BhDateRangePickerCustomEvent<SelectedDateRange | null>>;
};
export declare const BhDateRangePicker: StencilReactComponent<BhDateRangePickerElement, BhDateRangePickerEvents>;
type BhDateRangePickerContentEvents = {
    onBhChange: EventName<BhDateRangePickerContentCustomEvent<SelectedDateRange | null>>;
    onBhDateRangeSelect: EventName<BhDateRangePickerContentCustomEvent<SelectedDateRange | null>>;
};
export declare const BhDateRangePickerContent: StencilReactComponent<BhDateRangePickerContentElement, BhDateRangePickerContentEvents>;
type BhDropdownEvents = {
    onBhItemClick: EventName<BhDropdownCustomEvent<DropdownMenuItem>>;
};
export declare const BhDropdown: StencilReactComponent<BhDropdownElement, BhDropdownEvents>;
type BhDropdownMenuEvents = {
    onBhItemClick: EventName<BhDropdownMenuCustomEvent<DropdownMenuItem>>;
};
export declare const BhDropdownMenu: StencilReactComponent<BhDropdownMenuElement, BhDropdownMenuEvents>;
type BhEmptyStateEvents = {
    onBhPrimaryAction: EventName<CustomEvent<void>>;
    onBhSecondaryAction: EventName<CustomEvent<void>>;
};
export declare const BhEmptyState: StencilReactComponent<BhEmptyStateElement, BhEmptyStateEvents>;
type BhFeaturedIconEvents = NonNullable<unknown>;
export declare const BhFeaturedIcon: StencilReactComponent<BhFeaturedIconElement, BhFeaturedIconEvents>;
type BhIllustrationsEvents = NonNullable<unknown>;
export declare const BhIllustrations: StencilReactComponent<BhIllustrationsElement, BhIllustrationsEvents>;
type BhInputAutocompleteEvents = {
    onBhChange: EventName<CustomEvent<string>>;
    onBhSelectedItemsChange: EventName<BhInputAutocompleteCustomEvent<AutocompleteMenuItem[]>>;
    onBhFocus: EventName<CustomEvent<void>>;
    onBhBlur: EventName<CustomEvent<void>>;
    onBhHelpClick: EventName<CustomEvent<void>>;
    onBhOptionSelect: EventName<BhInputAutocompleteCustomEvent<AutocompleteMenuItem>>;
};
export declare const BhInputAutocomplete: StencilReactComponent<BhInputAutocompleteElement, BhInputAutocompleteEvents>;
type BhInputNumberEvents = {
    onBhChange: EventName<CustomEvent<number | null>>;
    onBhFocus: EventName<CustomEvent<void>>;
    onBhBlur: EventName<CustomEvent<void>>;
    onBhHelpClick: EventName<CustomEvent<void>>;
};
export declare const BhInputNumber: StencilReactComponent<BhInputNumberElement, BhInputNumberEvents>;
type BhInputPasswordEvents = {
    onBhInput: EventName<CustomEvent<string>>;
    onBhFocus: EventName<CustomEvent<void>>;
    onBhBlur: EventName<CustomEvent<void>>;
    onBhHelpClick: EventName<CustomEvent<void>>;
    onBhVisibilityToggle: EventName<CustomEvent<boolean>>;
};
export declare const BhInputPassword: StencilReactComponent<BhInputPasswordElement, BhInputPasswordEvents>;
type BhInputTextEvents = {
    onBhInput: EventName<CustomEvent<string>>;
    onBhFocus: EventName<CustomEvent<void>>;
    onBhBlur: EventName<CustomEvent<void>>;
    onBhHelpClick: EventName<CustomEvent<void>>;
};
export declare const BhInputText: StencilReactComponent<BhInputTextElement, BhInputTextEvents>;
type BhInputVerificationEvents = {
    onBhChange: EventName<CustomEvent<string>>;
    onBhComplete: EventName<CustomEvent<string>>;
};
export declare const BhInputVerification: StencilReactComponent<BhInputVerificationElement, BhInputVerificationEvents>;
type BhLabelEvents = {
    onBhHelpClick: EventName<CustomEvent<void>>;
};
export declare const BhLabel: StencilReactComponent<BhLabelElement, BhLabelEvents>;
type BhLoaderSpinnerEvents = NonNullable<unknown>;
export declare const BhLoaderSpinner: StencilReactComponent<BhLoaderSpinnerElement, BhLoaderSpinnerEvents>;
type BhLogoBoxEvents = {
    onBhProductSelect: EventName<BhLogoBoxCustomEvent<BhProduct>>;
};
export declare const BhLogoBox: StencilReactComponent<BhLogoBoxElement, BhLogoBoxEvents>;
type BhModalEvents = {
    onBhClose: EventName<CustomEvent<void>>;
};
export declare const BhModal: StencilReactComponent<BhModalElement, BhModalEvents>;
type BhModalActionsEvents = {
    onBhPrimaryAction: EventName<CustomEvent<void>>;
    onBhSecondaryAction: EventName<CustomEvent<void>>;
};
export declare const BhModalActions: StencilReactComponent<BhModalActionsElement, BhModalActionsEvents>;
type BhModalHeaderEvents = {
    onBhClose: EventName<CustomEvent<void>>;
};
export declare const BhModalHeader: StencilReactComponent<BhModalHeaderElement, BhModalHeaderEvents>;
type BhMonthPickerEvents = {
    onBhChange: EventName<BhMonthPickerCustomEvent<MonthYear | null>>;
    onBhMonthYearSelect: EventName<BhMonthPickerCustomEvent<MonthYear>>;
};
export declare const BhMonthPicker: StencilReactComponent<BhMonthPickerElement, BhMonthPickerEvents>;
type BhMonthPickerContentEvents = {
    onBhChange: EventName<BhMonthPickerContentCustomEvent<MonthYear>>;
    onBhMonthYearSelect: EventName<BhMonthPickerContentCustomEvent<MonthYear>>;
};
export declare const BhMonthPickerContent: StencilReactComponent<BhMonthPickerContentElement, BhMonthPickerContentEvents>;
type BhNavItemEvents = {
    onBhClick: EventName<CustomEvent<void>>;
};
export declare const BhNavItem: StencilReactComponent<BhNavItemElement, BhNavItemEvents>;
type BhNotificationEvents = {
    onBhAction: EventName<CustomEvent<void>>;
    onBhDismiss: EventName<CustomEvent<void>>;
    onBhClose: EventName<CustomEvent<void>>;
};
export declare const BhNotification: StencilReactComponent<BhNotificationElement, BhNotificationEvents>;
type BhPageNavigationEvents = {
    onBhItemClick: EventName<CustomEvent<{
        itemId: string;
        childIndex?: number;
    }>>;
};
export declare const BhPageNavigation: StencilReactComponent<BhPageNavigationElement, BhPageNavigationEvents>;
type BhPageNavigationChildEvents = {
    onBhItemClick: EventName<CustomEvent<void>>;
};
export declare const BhPageNavigationChild: StencilReactComponent<BhPageNavigationChildElement, BhPageNavigationChildEvents>;
type BhPageNavigationMultiLevelEvents = {
    onBhToggle: EventName<CustomEvent<void>>;
    onBhChildClick: EventName<CustomEvent<number>>;
    onBhAddClick: EventName<CustomEvent<void>>;
};
export declare const BhPageNavigationMultiLevel: StencilReactComponent<BhPageNavigationMultiLevelElement, BhPageNavigationMultiLevelEvents>;
type BhPageNavigationSingleLevelEvents = {
    onBhItemClick: EventName<CustomEvent<void>>;
};
export declare const BhPageNavigationSingleLevel: StencilReactComponent<BhPageNavigationSingleLevelElement, BhPageNavigationSingleLevelEvents>;
type BhPaginationEvents = {
    onBhPageChange: EventName<BhPaginationCustomEvent<PaginationChangeEvent>>;
    onBhPageSizeChange: EventName<BhPaginationCustomEvent<PaginationChangeEvent>>;
};
export declare const BhPagination: StencilReactComponent<BhPaginationElement, BhPaginationEvents>;
type BhPickerMenuEvents = {
    onBhChange: EventName<BhPickerMenuCustomEvent<MonthYear | null>>;
    onBhMonthYearSelect: EventName<BhPickerMenuCustomEvent<MonthYear>>;
    onBhCancel: EventName<CustomEvent<void>>;
    onBhApply: EventName<CustomEvent<void>>;
    onBhToday: EventName<CustomEvent<void>>;
};
export declare const BhPickerMenu: StencilReactComponent<BhPickerMenuElement, BhPickerMenuEvents>;
type BhPieChartEvents = NonNullable<unknown>;
export declare const BhPieChart: StencilReactComponent<BhPieChartElement, BhPieChartEvents>;
type BhPopoverEvents = {
    onBhItemSelect: EventName<BhPopoverCustomEvent<PopoverItem>>;
    onBhPortfolioClick: EventName<CustomEvent<void>>;
    onBhSearchChange: EventName<CustomEvent<string>>;
};
export declare const BhPopover: StencilReactComponent<BhPopoverElement, BhPopoverEvents>;
type BhProductSwitcherEvents = {
    onBhClose: EventName<CustomEvent<void>>;
    onBhProductSelect: EventName<BhProductSwitcherCustomEvent<BhProduct>>;
};
export declare const BhProductSwitcher: StencilReactComponent<BhProductSwitcherElement, BhProductSwitcherEvents>;
type BhPropertySwitcherEvents = {
    onBhPropertyChange: EventName<BhPropertySwitcherCustomEvent<PropertyOption>>;
};
export declare const BhPropertySwitcher: StencilReactComponent<BhPropertySwitcherElement, BhPropertySwitcherEvents>;
type BhRadioButtonEvents = {
    onBhChange: EventName<CustomEvent<string>>;
};
export declare const BhRadioButton: StencilReactComponent<BhRadioButtonElement, BhRadioButtonEvents>;
type BhSidebarEvents = {
    onBhMenuItemClick: EventName<CustomEvent<string>>;
    onBhSearchClick: EventName<CustomEvent<void>>;
    onBhAvatarMenuClick: EventName<BhSidebarCustomEvent<DropdownMenuItem>>;
};
export declare const BhSidebar: StencilReactComponent<BhSidebarElement, BhSidebarEvents>;
type BhSkeletonLoaderEvents = NonNullable<unknown>;
export declare const BhSkeletonLoader: StencilReactComponent<BhSkeletonLoaderElement, BhSkeletonLoaderEvents>;
type BhTabItemEvents = {
    onBhTabItemClick: EventName<CustomEvent<string>>;
};
export declare const BhTabItem: StencilReactComponent<BhTabItemElement, BhTabItemEvents>;
type BhTabsEvents = {
    onBhTabChange: EventName<CustomEvent<string>>;
};
export declare const BhTabs: StencilReactComponent<BhTabsElement, BhTabsEvents>;
type BhTagEvents = {
    onBhDismiss: EventName<CustomEvent<void>>;
};
export declare const BhTag: StencilReactComponent<BhTagElement, BhTagEvents>;
type BhTextareaEvents = {
    onBhInput: EventName<CustomEvent<string>>;
    onBhFocus: EventName<CustomEvent<void>>;
    onBhBlur: EventName<CustomEvent<void>>;
    onBhHelpClick: EventName<CustomEvent<void>>;
};
export declare const BhTextarea: StencilReactComponent<BhTextareaElement, BhTextareaEvents>;
type BhToggleEvents = {
    onBhChange: EventName<CustomEvent<boolean>>;
};
export declare const BhToggle: StencilReactComponent<BhToggleElement, BhToggleEvents>;
type BhTooltipEvents = NonNullable<unknown>;
export declare const BhTooltip: StencilReactComponent<BhTooltipElement, BhTooltipEvents>;
type BhTrendChartEvents = NonNullable<unknown>;
export declare const BhTrendChart: StencilReactComponent<BhTrendChartElement, BhTrendChartEvents>;
export {};
//# sourceMappingURL=components.server.d.ts.map