/**
 * Auto-generated React wrapper components
 *
 * This file exports all React wrapper components generated by @stencil/react-output-target.
 */
export * from './components';
//# sourceMappingURL=index.d.ts.map